Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: handler
      CodeUri: /home/renatofagalde/Documents/desenvolvimento/backend-site
      Runtime: go1.x
      Architectures:
        - x86_64