version: 0.2

env:
  variables:
    S3_BUCKET: "br.com.likwi.artifacts.apps.backend-site-dev"
    PACKAGE: "backend-site"

phases:
  pre_build:
    commands:
      - echo "Setting GOXX variables 🖖"
      - export GOOS=linux
      - export GOARCH=amd64
      - export CGO_ENABLED=0
      - echo "🚀 -> 🪣"
      - go mod tidy
      - go get -t ./...
      - go vet ./...
      - go test ./...

  build:
    commands:
      - env
      - go build *.go

      # Use a Docker image with an older GLIBC version for packaging
      - docker run --rm -v $(pwd):/app -w /app lambci/lambda:build-go1.x bash -c "aws cloudformation package --template-file template.yaml --s3-bucket ${S3_BUCKET} --output-template-file packaged.yaml"

artifacts:
  files:
    - packaged.yaml
