version: 0.2

env:
  variables:
    # This S3 bucket will be used to store the packaged Lambda deployment bundle.
    # Make sure to provide a valid S3 bucket name (it must exist already).
    # The AWS CodeBuild IAM role must allow write access to it.
    S3_BUCKET: "br.com.likwi.artifacts.apps.backend-site-dev"
    PACKAGE: "backend-site"

phases:

  install:
    runtime-versions:
      golang: 1.20
    commands:

      # AWS Codebuild Go images use /go for the $GOPATH so let's copy our
      # application source code into that directory structure.
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0

      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

      # Install golint
      # - go get -u github.com/golang/lint/golint

  pre_build:
    commands:

      # Make sure we're in the project directory within our GOPATH
      - cd "/go/src/${PACKAGE}"


      # Fetch all dependencies
      - go get -t ./...

      # Ensure code passes all lint tests
#      - golint -set_exit_status

      # Check the Go code for common problems with 'go vet'
      - go vet ./...

      # Run all tests included with our application
      - go test ./...

  build:
    commands:

#      - echo creating module ðŸ›ž
#      - go mod backend-site
#
#      # Build our go application
      - echo compilando ðŸ˜Ž
      - go build -o backend-site main.go
      - echo ðŸ†— -> ðŸ–¥ï¸
      - echo zipando ðŸ—ƒï¸
      - zip backend-site.zip backend-site
      - echo ðŸš€ -> ðŸª£
      - aws s3 cp ${PACKAGE}.zip s3://${S3_BUCKET}

      # Create packaged.yaml
      - aws cloudformation package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket ${S3_BUCKET}

      # Package our application with AWS SAM
      - echo ðŸ”¥ðŸ”¥ðŸ”¥ðŸ”¥ðŸ”¥ðŸ”¥ -> ðŸš€ -> ðŸª£
      - aws cloudformation deploy --template-file packaged.yaml --stack-name BackendSiteFunction --capabilities CAPABILITY_IAM

artifacts:
  files:
    - packaged.yaml