version: 0.2

env:
  variables:
    S3_BUCKET: "br.com.likwi.artifacts.apps.backend-site-dev"
    PACKAGE: "main"

phases:
  install:
    commands:
      # Install necessary tools for cross-compilation
      - yum install -y glibc-static
      - yum install -y libstdc++-static
      - yum install -y gcc
      - yum install -y gcc-c++

  pre_build:
    commands:
      - echo "Setting GOXX variables 🖖"
      - export GOOS=linux
      - export GOARCH=amd64
      - export CGO_ENABLED=0
      - echo "🚀 -> 🪣"
      - go mod tidy
      - go get -t ./...
      - go vet ./...
      - go test ./...

  build:
    commands:
      - echo "🚀 -> 🪣"
      - go build -o backend-site *.go
      - zip backend-site.zip backend-site
      - aws s3 cp backend-site.zip s3://br.com.likwi.artifacts.apps.backend-site-dev

      # Package the application with AWS SAM
      - aws cloudformation package --template-file template.yaml --s3-bucket ${S3_BUCKET} --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
