AWSTemplateFormatVersion: 2010-09-09
Description: backend site in golang
Parameters:
  Stage:
    Type: String
    Default: dev
  S3BucketName:
    Type: String
    Default: br.com.likwi.artifacts.apps.backend-site-dev
Resources:
  BackendSiteAppFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: backend-site-app-${Stage}
      Runtime: go1.x
      Handler: backend-site
      Description: site backend
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          Stage:
            Ref: Stage
      Code:
        S3Bucket:
          Ref: S3BucketName
        S3Key: backend-site.zip
      Role: arn:aws:iam::012821307542:role/LambdaExecutionRole
