AWSTemplateFormatVersion: 2010-09-09
Description: >-
  backend site in golang
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        Stage: !Ref Stage

Resources:
  BackendSiteAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub backend-site-app-${Stage}
      Runtime: go1.x
      CodeUri: .
      Handler: backend-site
      Description: Call the AWS Lambda API
      Timeout: 300
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - SecretsManagerReadPolicy
      Tracing: Active
      Environment:
        Variables:
          Stage: !Ref Stage

  SecretsManagerReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SecretsManagerReadPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: "*"