AWSTemplateFormatVersion: 2010-09-09
Description: >-
  backend-site 39
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        Stage: !Ref Stage


Resources:
  BackendSite:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: backend-site-dev
      Runtime: go1.x
      CodeUri: .
      Handler: backend-site
      Description: Suport all websites
      Timeout: 50
      Role: !GetAtt IAMRole.Arn
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      # Configuração do CloudWatch Logs
      LogGroupName: /aws/lambda/dev/backend-site-dev
      LogStreamName: { "Fn::Join": [ "", [ "/aws/lambda/backend-site-dev", { "Ref": "AWS::StackName" } ] ] }
      LogRetentionInDays: 7  # Define o tempo de retenção dos logs no CloudWatch

  IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: "Lambdapermissions"
      AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
      ManagedPolicyArns:
        - !Ref IAMManagedPolicy
      Description: "Allows Lambda functions to call AWS services on your behalf."

  IAMManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: "LambdaSecretsPolicy"
      Path: "/"
      PolicyDocument: |
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "Statement1",
                    "Effect": "Allow",
                    "Action": [
                        "secretsmanager:GetSecretValue",
                        "ec2:CreateNetworkInterface",
                        "ec2:DescribeNetworkInterfaces",
                        "ec2:DeleteNetworkInterface"
                    ],
                    "Resource": "*"
                }
            ]
        }

Outputs:
  BackendSiteFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt BackendSite.Arn
  BackendSiteFunctionFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt BackendSite.Arn