AWSTemplateFormatVersion: 2010-09-09
Description: >-
  backend-site 39
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        Stage: !Ref Stage

Resources:
  BackendSite:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: backend-site-dev
      Runtime: go1.x
      CodeUri: .
      Handler: backend-site
      Description: Call the AWS Lambda API
      Timeout: 50
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active


Outputs:
  BackendSiteFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt BackendSite.Arn
  BackendSiteFunctionFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt BackendSite.Arn