AWSTemplateFormatVersion: 2010-09-09
Description: backend site in golang
Parameters:
  Stage:
    Type: String
    Default: dev
  S3BucketName:
    Type: String
    Default: br.com.likwi.artifacts.apps.backend-site-dev
  LambdaFunctionRole:
    Description: arn do IAM da role que sera usada para deploy da lambda
    Type: AWS::SSM::Parameter::Value<String>
    Default:

Resources:
  BackendSiteAppFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: backend-site-app-${Stage}
      Runtime: go1.x
      Handler: backend-site
      Description: Call the AWS Lambda API
      Timeout: 300
      MemorySize: 64
      Environment:
        Variables:
          Stage: !Ref Stage
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: backend-site.zip
      Role: !GetAtt LambdaExecutionRole.Arn
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
#        - PolicyName: RDSAccessPolicy
#          PolicyDocument:
#            Version: '2012-10-17'
#            Statement:
#              - Effect: Allow
#                Action:
#                  - rds-db:connect
#                Resource: "arn:aws:rds-db:REGION:012821307542:dbuser/DB_INSTANCE_NAME/DB_USERNAME"
#        - PolicyName: SQSAccessPolicy
#          PolicyDocument:
#            Version: '2012-10-17'
#            Statement:
#              - Effect: Allow
#                Action:
#                  - sqs:SendMessage
#                  - sqs:ReceiveMessage
#                  - sqs:DeleteMessage
#                Resource: "arn:aws:sqs:REGION:ACCOUNT_ID:QUEUE_NAME"
        - PolicyName: SecretsManagerAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:us-east-1:012821307542:secret:dev/mysql/api"