



AWSTemplateFormatVersion: 2010-09-09
Description: backend site in golang
Parameters:
  Stage:
    Type: String
    Default: dev
  S3BucketName:
    Type: String
    Default: br.com.likwi.artifacts.apps.backend-site-dev
  LambdaFunctionRole:
    Description: arn do IAM da role que sera usada para deploy da lambda
    Type: AWS::SSM::Parameter::Value<String>
    Default:

Resources:
  BackendSiteAppFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: backend-site-app-${Stage}
      Runtime: go1.x
      Handler: backend-site
      Description: Call the AWS Lambda API
      Timeout: 300
      MemorySize: 64
      Environment:
        Variables:
          Stage: !Ref Stage
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: backend-site.zip
      Role: arn:aws:iam::012821307542:role/codecommit-api-role
