AWSTemplateFormatVersion: 2010-09-09
Description: >-
  backend-site 39
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        Stage: !Ref Stage

Resources:
  BackendSite:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: backend-site-dev
      Runtime: go1.x
      CodeUri: /home/runner/work/backend-site
      Handler: backend-site
      Description: Suport all websites
      Timeout: 50
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - SecretsManagerReadPolicy
      Tracing: Active

  # New policy for Secrets Manager read access
  SecretsManagerReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SecretsManagerReadPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - arn:aws:secretsmanager:us-east-1:012821307542:secret:dev/mysql/api-jNAmkR

Outputs:
  BackendSiteFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt BackendSite.Arn
  BackendSiteFunctionFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt BackendSite.Arn