AWSTemplateFormatVersion: 2010-09-09
Description: backend site in golang
Parameters:
  Stage:
    Type: String
    Default: dev
  S3BucketName:
    Type: String
    Default: br.com.likwi.artifacts.apps.backend-site-dev

Resources:
  BackendSiteAppFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "backend-site-app-${Stage}"
      Runtime: go1.x
      Handler: backend-site
      Description: site backend
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          Stage: !Ref Stage
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: backend-site.zip
      Role: !If
        - LambdaExecutionRoleExists
        - !GetAtt LambdaExecutionRole.Arn
        - !Ref "AWS::NoValue"
    DependsOn: [SiteLogGroup,LambdaExecutionRole]

  SiteLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/api/lambda/backendsite"
      RetentionInDays: 3

Transform:
  - Name: 'AWS::Serverless-2016-10-31'
    Parameters:
      LambdaExecutionRoleExists:
        Type: String
        Description: 'Indicates whether Lambda execution role already exists or not.'
